### ISSUE TITLE
Does not work with Node.js 0.12

### ISSUE THREAD

**Issue by tonila** [Hexagon/node-telldus#65]
npm install prints following errors:

http://pastebin.com/dgvH4ud6

**Comment by freber** [comment]
Please fix :)

**Comment by emiloberg** [comment]
+1

**Comment by kenderson** [comment]
+1

**Comment by Zebusch** [comment]
I have forked this repo and made some changes. Not complete though but at least i can use it with sensors. https://github.com/Zebusch/node-telldus-zb

**Comment by Hexagon** [comment]
Sorry about the delay! Now there's a new branch called experimental, please clone it, test it, fork it and fix it!

@Zebush , I decided to start over from scratch as your code didn't compile on 5.1, and because I had to learn the new changes of V8 myself. But i did get a lot of help looking at your code, and i reused some of it. Thanks :)

**Comment by Hexagon** [comment]
v4.2 and 5.1 seem to work fine. Trying 0.12 as soon as it has compiled.

@emiloberg , could you try it against node-red-contrib-tellstick ?

**Comment by Hexagon** [comment]
Well, now it's released :)

**Comment by emiloberg** [comment]
Well done! :star: I'll let you know if me or any of my users run in to any problems!
